supporting for multi repo
codefresh-contrib/cfstep-helm pull request #96
Opened 2023-01-24 09:43 UTC by andrii-codefresh

2023-01-26 14:52 UTC, denis-codefresh approved these changes

2023-01-30 15:00 UTC, pasha-codefresh requested changes

2023-01-30 15:00 UTC, pasha-codefresh commented on lib/EntrypointScriptBuilder.py
> +                repo_name = key[7:len(key) - 4]
add example

2023-01-30 15:00 UTC, pasha-codefresh commented on lib/EntrypointScriptBuilder.py
> +                self.chart_repo_url = repo_url
check if needed

2023-01-30 15:00 UTC, pasha-codefresh commented on lib/EntrypointScriptBuilder.py
> +        if (self.use_repos_for_auth_action.upper() == 'TRUE') or (self.action != 'auth'):
convert to boolean before

2023-01-30 15:00 UTC, pasha-codefresh commented on lib/EntrypointScriptBuilder.py
> +                helm_repo_username = os.getenv('CF_CTX_' + repo_name.upper() + '_HELMREPO_USERNAME')
reuse get credentials ffunction

2023-01-30 15:07 UTC, andrii-codefresh commented on lib/EntrypointScriptBuilder.py
> +                self.chart_repo_url = repo_url
checked. it is OK

2023-01-30 15:40 UTC, pasha-codefresh approved these changes

2023-01-30 15:43 UTC, merged